/*
 * generated by Xtext 2.14.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import project.ui.internal.ProjectActivator;

public class BankSystemUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ProjectActivator.getInstance().getInjector("org.xtext.BankSystem");
	}

}
