/*
 * generated by Xtext 2.14.0
 */
package org.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBankSystemScopeProvider extends DelegatingScopeProvider {
}
