/*
 * generated by Xtext 2.14.0
 */
package org.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BankSystemStandaloneSetup extends BankSystemStandaloneSetupGenerated {

	def static void doSetup() {
		new BankSystemStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
