/**
 * generated by Xtext 2.14.0
 */
package org.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.BankSystemRuntimeModule;
import org.xtext.BankSystemStandaloneSetup;
import org.xtext.ide.BankSystemIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class BankSystemIdeSetup extends BankSystemStandaloneSetup {
  @Override
  public Injector createInjector() {
    BankSystemRuntimeModule _bankSystemRuntimeModule = new BankSystemRuntimeModule();
    BankSystemIdeModule _bankSystemIdeModule = new BankSystemIdeModule();
    return Guice.createInjector(Modules2.mixin(_bankSystemRuntimeModule, _bankSystemIdeModule));
  }
}
