/**
 * generated by Xtext 2.14.0
 */
package org.xtext.ide;

import org.xtext.ide.AbstractBankSystemIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class BankSystemIdeModule extends AbstractBankSystemIdeModule {
}
