/*
 * generated by Xtext 2.14.0
 */
package org.xtext.validation
import org.eclipse.xtext.validation.Check
import org.xtext.bankSystem.BankSystem
import org.xtext.bankSystem.BankSystemPackage
import org.xtext.bankSystem.Account

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class BankSystemValidator extends AbstractBankSystemValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					BankSystemPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	public static val WRONG_ACCOUNT_ATTRIBUTE = 'wrongAccountAttibute'
	@Check
	def void checkAccountTypeAttribute(Account account){
		if(account.getAccountType().equals("Savings Account") && account.intRate == 0){
			warning('A savings account should have an interest rate',BankSystemPackage.Literals.ACCOUNT__INT_RATE, WRONG_ACCOUNT_ATTRIBUTE)
		}
		if(account.getAccountType().equals("Mortgage Account") && account.loanPeriod.length()< 1){
			warning('A mortgage account should have a loan period',BankSystemPackage.Literals.ACCOUNT__LOAN_PERIOD, WRONG_ACCOUNT_ATTRIBUTE)
		}
		if(account.getAccountType().equals("Checking Account") && account.debPerMonth == 0){
			warning('A checking account should have a debit per month attribute',BankSystemPackage.Literals.ACCOUNT__DEB_PER_MONTH, WRONG_ACCOUNT_ATTRIBUTE)
		}
	}
}
