/*
 * generated by Xtext 2.14.0
 */
package org.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import project.ui.internal.ProjectActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BankSystemExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ProjectActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ProjectActivator activator = ProjectActivator.getInstance();
		return activator != null ? activator.getInjector(ProjectActivator.ORG_XTEXT_BANKSYSTEM) : null;
	}

}
