/**
 * generated by Xtext 2.14.0
 */
package org.xtext.bankSystem;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bank System</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.bankSystem.BankSystem#getBanks <em>Banks</em>}</li>
 *   <li>{@link org.xtext.bankSystem.BankSystem#getUsers <em>Users</em>}</li>
 * </ul>
 *
 * @see org.xtext.bankSystem.BankSystemPackage#getBankSystem()
 * @model
 * @generated
 */
public interface BankSystem extends EObject
{
  /**
   * Returns the value of the '<em><b>Banks</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.bankSystem.Bank}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Banks</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Banks</em>' containment reference list.
   * @see org.xtext.bankSystem.BankSystemPackage#getBankSystem_Banks()
   * @model containment="true"
   * @generated
   */
  EList<Bank> getBanks();

  /**
   * Returns the value of the '<em><b>Users</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.bankSystem.User}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Users</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Users</em>' containment reference list.
   * @see org.xtext.bankSystem.BankSystemPackage#getBankSystem_Users()
   * @model containment="true"
   * @generated
   */
  EList<User> getUsers();

} // BankSystem
