/**
 * generated by Xtext 2.14.0
 */
package org.xtext.bankSystem;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bank</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.bankSystem.Bank#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.bankSystem.Bank#getCountryOfOrigin <em>Country Of Origin</em>}</li>
 *   <li>{@link org.xtext.bankSystem.Bank#getBranches <em>Branches</em>}</li>
 *   <li>{@link org.xtext.bankSystem.Bank#getAccounts <em>Accounts</em>}</li>
 *   <li>{@link org.xtext.bankSystem.Bank#getTransactions <em>Transactions</em>}</li>
 * </ul>
 *
 * @see org.xtext.bankSystem.BankSystemPackage#getBank()
 * @model
 * @generated
 */
public interface Bank extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.bankSystem.BankSystemPackage#getBank_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.bankSystem.Bank#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Country Of Origin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Country Of Origin</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Country Of Origin</em>' attribute.
   * @see #setCountryOfOrigin(String)
   * @see org.xtext.bankSystem.BankSystemPackage#getBank_CountryOfOrigin()
   * @model
   * @generated
   */
  String getCountryOfOrigin();

  /**
   * Sets the value of the '{@link org.xtext.bankSystem.Bank#getCountryOfOrigin <em>Country Of Origin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Country Of Origin</em>' attribute.
   * @see #getCountryOfOrigin()
   * @generated
   */
  void setCountryOfOrigin(String value);

  /**
   * Returns the value of the '<em><b>Branches</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.bankSystem.Branch}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Branches</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Branches</em>' containment reference list.
   * @see org.xtext.bankSystem.BankSystemPackage#getBank_Branches()
   * @model containment="true"
   * @generated
   */
  EList<Branch> getBranches();

  /**
   * Returns the value of the '<em><b>Accounts</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.bankSystem.Account}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Accounts</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Accounts</em>' containment reference list.
   * @see org.xtext.bankSystem.BankSystemPackage#getBank_Accounts()
   * @model containment="true"
   * @generated
   */
  EList<Account> getAccounts();

  /**
   * Returns the value of the '<em><b>Transactions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.bankSystem.Transaction}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Transactions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transactions</em>' containment reference list.
   * @see org.xtext.bankSystem.BankSystemPackage#getBank_Transactions()
   * @model containment="true"
   * @generated
   */
  EList<Transaction> getTransactions();

} // Bank
