/**
 * generated by Xtext 2.14.0
 */
package org.xtext.bankSystem;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Checking Account</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.bankSystem.CheckingAccount#getDepPerMonth <em>Dep Per Month</em>}</li>
 * </ul>
 *
 * @see org.xtext.bankSystem.BankSystemPackage#getCheckingAccount()
 * @model
 * @generated
 */
public interface CheckingAccount extends Account
{
  /**
   * Returns the value of the '<em><b>Dep Per Month</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dep Per Month</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dep Per Month</em>' attribute.
   * @see #setDepPerMonth(int)
   * @see org.xtext.bankSystem.BankSystemPackage#getCheckingAccount_DepPerMonth()
   * @model
   * @generated
   */
  int getDepPerMonth();

  /**
   * Sets the value of the '{@link org.xtext.bankSystem.CheckingAccount#getDepPerMonth <em>Dep Per Month</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dep Per Month</em>' attribute.
   * @see #getDepPerMonth()
   * @generated
   */
  void setDepPerMonth(int value);

} // CheckingAccount
