/**
 * generated by Xtext 2.14.0
 */
package org.xtext.bankSystem;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Employee</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.bankSystem.Employee#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.bankSystem.Employee#getDate <em>Date</em>}</li>
 *   <li>{@link org.xtext.bankSystem.Employee#getSalary <em>Salary</em>}</li>
 *   <li>{@link org.xtext.bankSystem.Employee#getCurrentRole <em>Current Role</em>}</li>
 * </ul>
 *
 * @see org.xtext.bankSystem.BankSystemPackage#getEmployee()
 * @model
 * @generated
 */
public interface Employee extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.bankSystem.BankSystemPackage#getEmployee_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.bankSystem.Employee#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Date</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Date</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date</em>' containment reference.
   * @see #setDate(Date)
   * @see org.xtext.bankSystem.BankSystemPackage#getEmployee_Date()
   * @model containment="true"
   * @generated
   */
  Date getDate();

  /**
   * Sets the value of the '{@link org.xtext.bankSystem.Employee#getDate <em>Date</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Date</em>' containment reference.
   * @see #getDate()
   * @generated
   */
  void setDate(Date value);

  /**
   * Returns the value of the '<em><b>Salary</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Salary</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Salary</em>' attribute.
   * @see #setSalary(int)
   * @see org.xtext.bankSystem.BankSystemPackage#getEmployee_Salary()
   * @model
   * @generated
   */
  int getSalary();

  /**
   * Sets the value of the '{@link org.xtext.bankSystem.Employee#getSalary <em>Salary</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Salary</em>' attribute.
   * @see #getSalary()
   * @generated
   */
  void setSalary(int value);

  /**
   * Returns the value of the '<em><b>Current Role</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Current Role</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Current Role</em>' attribute.
   * @see #setCurrentRole(String)
   * @see org.xtext.bankSystem.BankSystemPackage#getEmployee_CurrentRole()
   * @model
   * @generated
   */
  String getCurrentRole();

  /**
   * Sets the value of the '{@link org.xtext.bankSystem.Employee#getCurrentRole <em>Current Role</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Current Role</em>' attribute.
   * @see #getCurrentRole()
   * @generated
   */
  void setCurrentRole(String value);

} // Employee
