/**
 * generated by Xtext 2.14.0
 */
package org.xtext.bankSystem;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mortgage Account</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.bankSystem.MortgageAccount#getLoanPeriod <em>Loan Period</em>}</li>
 * </ul>
 *
 * @see org.xtext.bankSystem.BankSystemPackage#getMortgageAccount()
 * @model
 * @generated
 */
public interface MortgageAccount extends Account
{
  /**
   * Returns the value of the '<em><b>Loan Period</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Loan Period</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loan Period</em>' attribute.
   * @see #setLoanPeriod(String)
   * @see org.xtext.bankSystem.BankSystemPackage#getMortgageAccount_LoanPeriod()
   * @model
   * @generated
   */
  String getLoanPeriod();

  /**
   * Sets the value of the '{@link org.xtext.bankSystem.MortgageAccount#getLoanPeriod <em>Loan Period</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Loan Period</em>' attribute.
   * @see #getLoanPeriod()
   * @generated
   */
  void setLoanPeriod(String value);

} // MortgageAccount
