/**
 * generated by Xtext 2.14.0
 */
package org.xtext.bankSystem;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Savings Account</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.bankSystem.SavingsAccount#getIntRate <em>Int Rate</em>}</li>
 * </ul>
 *
 * @see org.xtext.bankSystem.BankSystemPackage#getSavingsAccount()
 * @model
 * @generated
 */
public interface SavingsAccount extends Account
{
  /**
   * Returns the value of the '<em><b>Int Rate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Int Rate</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int Rate</em>' attribute.
   * @see #setIntRate(int)
   * @see org.xtext.bankSystem.BankSystemPackage#getSavingsAccount_IntRate()
   * @model
   * @generated
   */
  int getIntRate();

  /**
   * Sets the value of the '{@link org.xtext.bankSystem.SavingsAccount#getIntRate <em>Int Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int Rate</em>' attribute.
   * @see #getIntRate()
   * @generated
   */
  void setIntRate(int value);

} // SavingsAccount
