/**
 * generated by Xtext 2.14.0
 */
package org.xtext.bankSystem;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transaction</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.bankSystem.Transaction#getAccount <em>Account</em>}</li>
 *   <li>{@link org.xtext.bankSystem.Transaction#getAmount <em>Amount</em>}</li>
 *   <li>{@link org.xtext.bankSystem.Transaction#getDate <em>Date</em>}</li>
 *   <li>{@link org.xtext.bankSystem.Transaction#getDebit <em>Debit</em>}</li>
 *   <li>{@link org.xtext.bankSystem.Transaction#getVendorName <em>Vendor Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.bankSystem.BankSystemPackage#getTransaction()
 * @model
 * @generated
 */
public interface Transaction extends EObject
{
  /**
   * Returns the value of the '<em><b>Account</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Account</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Account</em>' attribute.
   * @see #setAccount(String)
   * @see org.xtext.bankSystem.BankSystemPackage#getTransaction_Account()
   * @model
   * @generated
   */
  String getAccount();

  /**
   * Sets the value of the '{@link org.xtext.bankSystem.Transaction#getAccount <em>Account</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Account</em>' attribute.
   * @see #getAccount()
   * @generated
   */
  void setAccount(String value);

  /**
   * Returns the value of the '<em><b>Amount</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Amount</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Amount</em>' attribute.
   * @see #setAmount(int)
   * @see org.xtext.bankSystem.BankSystemPackage#getTransaction_Amount()
   * @model
   * @generated
   */
  int getAmount();

  /**
   * Sets the value of the '{@link org.xtext.bankSystem.Transaction#getAmount <em>Amount</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Amount</em>' attribute.
   * @see #getAmount()
   * @generated
   */
  void setAmount(int value);

  /**
   * Returns the value of the '<em><b>Date</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Date</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Date</em>' containment reference.
   * @see #setDate(Date)
   * @see org.xtext.bankSystem.BankSystemPackage#getTransaction_Date()
   * @model containment="true"
   * @generated
   */
  Date getDate();

  /**
   * Sets the value of the '{@link org.xtext.bankSystem.Transaction#getDate <em>Date</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Date</em>' containment reference.
   * @see #getDate()
   * @generated
   */
  void setDate(Date value);

  /**
   * Returns the value of the '<em><b>Debit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Debit</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Debit</em>' attribute.
   * @see #setDebit(String)
   * @see org.xtext.bankSystem.BankSystemPackage#getTransaction_Debit()
   * @model
   * @generated
   */
  String getDebit();

  /**
   * Sets the value of the '{@link org.xtext.bankSystem.Transaction#getDebit <em>Debit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Debit</em>' attribute.
   * @see #getDebit()
   * @generated
   */
  void setDebit(String value);

  /**
   * Returns the value of the '<em><b>Vendor Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Vendor Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vendor Name</em>' attribute.
   * @see #setVendorName(String)
   * @see org.xtext.bankSystem.BankSystemPackage#getTransaction_VendorName()
   * @model
   * @generated
   */
  String getVendorName();

  /**
   * Sets the value of the '{@link org.xtext.bankSystem.Transaction#getVendorName <em>Vendor Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vendor Name</em>' attribute.
   * @see #getVendorName()
   * @generated
   */
  void setVendorName(String value);

} // Transaction
