/*
 * generated by Xtext 2.14.0
 */
package org.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.parser.antlr.internal.InternalBankSystemParser;
import org.xtext.services.BankSystemGrammarAccess;

public class BankSystemParser extends AbstractAntlrParser {

	@Inject
	private BankSystemGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBankSystemParser createParser(XtextTokenStream stream) {
		return new InternalBankSystemParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "BankSystem";
	}

	public BankSystemGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BankSystemGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
