/**
 * generated by Xtext 2.14.0
 */
package org.xtext.bankSystem.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.bankSystem.Account;
import org.xtext.bankSystem.BankSystemPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Account</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.bankSystem.impl.AccountImpl#getAccountNum <em>Account Num</em>}</li>
 *   <li>{@link org.xtext.bankSystem.impl.AccountImpl#getHolder <em>Holder</em>}</li>
 *   <li>{@link org.xtext.bankSystem.impl.AccountImpl#getBalance <em>Balance</em>}</li>
 *   <li>{@link org.xtext.bankSystem.impl.AccountImpl#getMfaType <em>Mfa Type</em>}</li>
 *   <li>{@link org.xtext.bankSystem.impl.AccountImpl#getAccountType <em>Account Type</em>}</li>
 *   <li>{@link org.xtext.bankSystem.impl.AccountImpl#getIntRate <em>Int Rate</em>}</li>
 *   <li>{@link org.xtext.bankSystem.impl.AccountImpl#getDepPerMonth <em>Dep Per Month</em>}</li>
 *   <li>{@link org.xtext.bankSystem.impl.AccountImpl#getLoanPeriod <em>Loan Period</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AccountImpl extends MinimalEObjectImpl.Container implements Account
{
  /**
   * The default value of the '{@link #getAccountNum() <em>Account Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAccountNum()
   * @generated
   * @ordered
   */
  protected static final String ACCOUNT_NUM_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAccountNum() <em>Account Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAccountNum()
   * @generated
   * @ordered
   */
  protected String accountNum = ACCOUNT_NUM_EDEFAULT;

  /**
   * The default value of the '{@link #getHolder() <em>Holder</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHolder()
   * @generated
   * @ordered
   */
  protected static final String HOLDER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHolder() <em>Holder</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHolder()
   * @generated
   * @ordered
   */
  protected String holder = HOLDER_EDEFAULT;

  /**
   * The default value of the '{@link #getBalance() <em>Balance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBalance()
   * @generated
   * @ordered
   */
  protected static final int BALANCE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getBalance() <em>Balance</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBalance()
   * @generated
   * @ordered
   */
  protected int balance = BALANCE_EDEFAULT;

  /**
   * The default value of the '{@link #getMfaType() <em>Mfa Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMfaType()
   * @generated
   * @ordered
   */
  protected static final String MFA_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getMfaType() <em>Mfa Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMfaType()
   * @generated
   * @ordered
   */
  protected String mfaType = MFA_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getAccountType() <em>Account Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAccountType()
   * @generated
   * @ordered
   */
  protected static final String ACCOUNT_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAccountType() <em>Account Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAccountType()
   * @generated
   * @ordered
   */
  protected String accountType = ACCOUNT_TYPE_EDEFAULT;

  /**
   * The default value of the '{@link #getIntRate() <em>Int Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntRate()
   * @generated
   * @ordered
   */
  protected static final int INT_RATE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getIntRate() <em>Int Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntRate()
   * @generated
   * @ordered
   */
  protected int intRate = INT_RATE_EDEFAULT;

  /**
   * The default value of the '{@link #getDepPerMonth() <em>Dep Per Month</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDepPerMonth()
   * @generated
   * @ordered
   */
  protected static final int DEP_PER_MONTH_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getDepPerMonth() <em>Dep Per Month</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDepPerMonth()
   * @generated
   * @ordered
   */
  protected int depPerMonth = DEP_PER_MONTH_EDEFAULT;

  /**
   * The default value of the '{@link #getLoanPeriod() <em>Loan Period</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoanPeriod()
   * @generated
   * @ordered
   */
  protected static final String LOAN_PERIOD_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLoanPeriod() <em>Loan Period</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoanPeriod()
   * @generated
   * @ordered
   */
  protected String loanPeriod = LOAN_PERIOD_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AccountImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BankSystemPackage.Literals.ACCOUNT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getAccountNum()
  {
    return accountNum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAccountNum(String newAccountNum)
  {
    String oldAccountNum = accountNum;
    accountNum = newAccountNum;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BankSystemPackage.ACCOUNT__ACCOUNT_NUM, oldAccountNum, accountNum));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getHolder()
  {
    return holder;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setHolder(String newHolder)
  {
    String oldHolder = holder;
    holder = newHolder;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BankSystemPackage.ACCOUNT__HOLDER, oldHolder, holder));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getBalance()
  {
    return balance;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setBalance(int newBalance)
  {
    int oldBalance = balance;
    balance = newBalance;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BankSystemPackage.ACCOUNT__BALANCE, oldBalance, balance));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getMfaType()
  {
    return mfaType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMfaType(String newMfaType)
  {
    String oldMfaType = mfaType;
    mfaType = newMfaType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BankSystemPackage.ACCOUNT__MFA_TYPE, oldMfaType, mfaType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getAccountType()
  {
    return accountType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAccountType(String newAccountType)
  {
    String oldAccountType = accountType;
    accountType = newAccountType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BankSystemPackage.ACCOUNT__ACCOUNT_TYPE, oldAccountType, accountType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getIntRate()
  {
    return intRate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIntRate(int newIntRate)
  {
    int oldIntRate = intRate;
    intRate = newIntRate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BankSystemPackage.ACCOUNT__INT_RATE, oldIntRate, intRate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getDepPerMonth()
  {
    return depPerMonth;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDepPerMonth(int newDepPerMonth)
  {
    int oldDepPerMonth = depPerMonth;
    depPerMonth = newDepPerMonth;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BankSystemPackage.ACCOUNT__DEP_PER_MONTH, oldDepPerMonth, depPerMonth));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLoanPeriod()
  {
    return loanPeriod;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLoanPeriod(String newLoanPeriod)
  {
    String oldLoanPeriod = loanPeriod;
    loanPeriod = newLoanPeriod;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BankSystemPackage.ACCOUNT__LOAN_PERIOD, oldLoanPeriod, loanPeriod));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BankSystemPackage.ACCOUNT__ACCOUNT_NUM:
        return getAccountNum();
      case BankSystemPackage.ACCOUNT__HOLDER:
        return getHolder();
      case BankSystemPackage.ACCOUNT__BALANCE:
        return getBalance();
      case BankSystemPackage.ACCOUNT__MFA_TYPE:
        return getMfaType();
      case BankSystemPackage.ACCOUNT__ACCOUNT_TYPE:
        return getAccountType();
      case BankSystemPackage.ACCOUNT__INT_RATE:
        return getIntRate();
      case BankSystemPackage.ACCOUNT__DEP_PER_MONTH:
        return getDepPerMonth();
      case BankSystemPackage.ACCOUNT__LOAN_PERIOD:
        return getLoanPeriod();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BankSystemPackage.ACCOUNT__ACCOUNT_NUM:
        setAccountNum((String)newValue);
        return;
      case BankSystemPackage.ACCOUNT__HOLDER:
        setHolder((String)newValue);
        return;
      case BankSystemPackage.ACCOUNT__BALANCE:
        setBalance((Integer)newValue);
        return;
      case BankSystemPackage.ACCOUNT__MFA_TYPE:
        setMfaType((String)newValue);
        return;
      case BankSystemPackage.ACCOUNT__ACCOUNT_TYPE:
        setAccountType((String)newValue);
        return;
      case BankSystemPackage.ACCOUNT__INT_RATE:
        setIntRate((Integer)newValue);
        return;
      case BankSystemPackage.ACCOUNT__DEP_PER_MONTH:
        setDepPerMonth((Integer)newValue);
        return;
      case BankSystemPackage.ACCOUNT__LOAN_PERIOD:
        setLoanPeriod((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BankSystemPackage.ACCOUNT__ACCOUNT_NUM:
        setAccountNum(ACCOUNT_NUM_EDEFAULT);
        return;
      case BankSystemPackage.ACCOUNT__HOLDER:
        setHolder(HOLDER_EDEFAULT);
        return;
      case BankSystemPackage.ACCOUNT__BALANCE:
        setBalance(BALANCE_EDEFAULT);
        return;
      case BankSystemPackage.ACCOUNT__MFA_TYPE:
        setMfaType(MFA_TYPE_EDEFAULT);
        return;
      case BankSystemPackage.ACCOUNT__ACCOUNT_TYPE:
        setAccountType(ACCOUNT_TYPE_EDEFAULT);
        return;
      case BankSystemPackage.ACCOUNT__INT_RATE:
        setIntRate(INT_RATE_EDEFAULT);
        return;
      case BankSystemPackage.ACCOUNT__DEP_PER_MONTH:
        setDepPerMonth(DEP_PER_MONTH_EDEFAULT);
        return;
      case BankSystemPackage.ACCOUNT__LOAN_PERIOD:
        setLoanPeriod(LOAN_PERIOD_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BankSystemPackage.ACCOUNT__ACCOUNT_NUM:
        return ACCOUNT_NUM_EDEFAULT == null ? accountNum != null : !ACCOUNT_NUM_EDEFAULT.equals(accountNum);
      case BankSystemPackage.ACCOUNT__HOLDER:
        return HOLDER_EDEFAULT == null ? holder != null : !HOLDER_EDEFAULT.equals(holder);
      case BankSystemPackage.ACCOUNT__BALANCE:
        return balance != BALANCE_EDEFAULT;
      case BankSystemPackage.ACCOUNT__MFA_TYPE:
        return MFA_TYPE_EDEFAULT == null ? mfaType != null : !MFA_TYPE_EDEFAULT.equals(mfaType);
      case BankSystemPackage.ACCOUNT__ACCOUNT_TYPE:
        return ACCOUNT_TYPE_EDEFAULT == null ? accountType != null : !ACCOUNT_TYPE_EDEFAULT.equals(accountType);
      case BankSystemPackage.ACCOUNT__INT_RATE:
        return intRate != INT_RATE_EDEFAULT;
      case BankSystemPackage.ACCOUNT__DEP_PER_MONTH:
        return depPerMonth != DEP_PER_MONTH_EDEFAULT;
      case BankSystemPackage.ACCOUNT__LOAN_PERIOD:
        return LOAN_PERIOD_EDEFAULT == null ? loanPeriod != null : !LOAN_PERIOD_EDEFAULT.equals(loanPeriod);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (accountNum: ");
    result.append(accountNum);
    result.append(", holder: ");
    result.append(holder);
    result.append(", balance: ");
    result.append(balance);
    result.append(", mfaType: ");
    result.append(mfaType);
    result.append(", accountType: ");
    result.append(accountType);
    result.append(", intRate: ");
    result.append(intRate);
    result.append(", depPerMonth: ");
    result.append(depPerMonth);
    result.append(", loanPeriod: ");
    result.append(loanPeriod);
    result.append(')');
    return result.toString();
  }

} //AccountImpl
