/**
 * generated by Xtext 2.14.0
 */
package org.xtext.bankSystem.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.bankSystem.BankSystemPackage;
import org.xtext.bankSystem.MortgageAccount;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Mortgage Account</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.bankSystem.impl.MortgageAccountImpl#getLoanPeriod <em>Loan Period</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MortgageAccountImpl extends AccountImpl implements MortgageAccount
{
  /**
   * The default value of the '{@link #getLoanPeriod() <em>Loan Period</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoanPeriod()
   * @generated
   * @ordered
   */
  protected static final String LOAN_PERIOD_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getLoanPeriod() <em>Loan Period</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoanPeriod()
   * @generated
   * @ordered
   */
  protected String loanPeriod = LOAN_PERIOD_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MortgageAccountImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BankSystemPackage.Literals.MORTGAGE_ACCOUNT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getLoanPeriod()
  {
    return loanPeriod;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLoanPeriod(String newLoanPeriod)
  {
    String oldLoanPeriod = loanPeriod;
    loanPeriod = newLoanPeriod;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BankSystemPackage.MORTGAGE_ACCOUNT__LOAN_PERIOD, oldLoanPeriod, loanPeriod));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BankSystemPackage.MORTGAGE_ACCOUNT__LOAN_PERIOD:
        return getLoanPeriod();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BankSystemPackage.MORTGAGE_ACCOUNT__LOAN_PERIOD:
        setLoanPeriod((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BankSystemPackage.MORTGAGE_ACCOUNT__LOAN_PERIOD:
        setLoanPeriod(LOAN_PERIOD_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BankSystemPackage.MORTGAGE_ACCOUNT__LOAN_PERIOD:
        return LOAN_PERIOD_EDEFAULT == null ? loanPeriod != null : !LOAN_PERIOD_EDEFAULT.equals(loanPeriod);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (loanPeriod: ");
    result.append(loanPeriod);
    result.append(')');
    return result.toString();
  }

} //MortgageAccountImpl
