/**
 * generated by Xtext 2.14.0
 */
package org.xtext.bankSystem.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.bankSystem.BankSystemPackage;
import org.xtext.bankSystem.SavingsAccount;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Savings Account</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.bankSystem.impl.SavingsAccountImpl#getIntRate <em>Int Rate</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SavingsAccountImpl extends AccountImpl implements SavingsAccount
{
  /**
   * The default value of the '{@link #getIntRate() <em>Int Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntRate()
   * @generated
   * @ordered
   */
  protected static final int INT_RATE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getIntRate() <em>Int Rate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIntRate()
   * @generated
   * @ordered
   */
  protected int intRate = INT_RATE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SavingsAccountImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BankSystemPackage.Literals.SAVINGS_ACCOUNT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getIntRate()
  {
    return intRate;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIntRate(int newIntRate)
  {
    int oldIntRate = intRate;
    intRate = newIntRate;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BankSystemPackage.SAVINGS_ACCOUNT__INT_RATE, oldIntRate, intRate));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BankSystemPackage.SAVINGS_ACCOUNT__INT_RATE:
        return getIntRate();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BankSystemPackage.SAVINGS_ACCOUNT__INT_RATE:
        setIntRate((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BankSystemPackage.SAVINGS_ACCOUNT__INT_RATE:
        setIntRate(INT_RATE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BankSystemPackage.SAVINGS_ACCOUNT__INT_RATE:
        return intRate != INT_RATE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (intRate: ");
    result.append(intRate);
    result.append(')');
    return result.toString();
  }

} //SavingsAccountImpl
