/*
 * generated by Xtext 2.14.0
 */
package org.xtext.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.BankSystemRuntimeModule
import org.xtext.BankSystemStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class BankSystemIdeSetup extends BankSystemStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new BankSystemRuntimeModule, new BankSystemIdeModule))
	}
	
}
